site_name: uv-demo
repo_url: https://github.com/deadhand777/uv-demo
site_url: https://deadhand777.github.io/uv-demo
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Chris
edit_uri: edit/main/docs/
repo_name: deadhand777/uv-demo
copyright: Maintained by <a href="https://deadhand777.com">chris</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [uv_demo]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deadhand777/uv-demo
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/uv-demo

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
